# Mandatory settings

blog_theme: dark # Or use light
name: Scott Lau
paginate: 25
url: https://www.liuweigeek.com

# markdown: redcarpet

# Optional settings

about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
#discus_identifier: false # Add your Disqus identifier
ga_analytics: UA-28631876-6 # Add your GA Tracking Id
local_fonts: false # Change to true if you wish to use local fonts
rss_enabled: false # Change to false if not
scrollappear_enabled: true # Change to false to disable
tag_nav_enabled: true # Change to true if you wish to show an additional 'tag-list' navigation below the header
theme_toggle: true # Change to true if you wish to show an icon in the navigation for dynamic theme toggling
social:
  #  dribbble: https://dribbble.com/liuweigeek # Add your Dribbble handle
  instagram: liuweigeek # Add your Instagram handle
  facebook: liuweigeek # Add your Facebook handle
  twitter: liuweigeek # Add your Twitter handle
  github: liuweigeek # Add your GitHub handle
  #  linkedin: # Add your LinkedIn handle
  email: liuweigeek@outlook.com # Add your Email address
  #  docker: # Add your Docker Hub handle
  #  stackoverflow: # Add your Stack Overflow ID number

# Important settings (change at own risk)

assets:
  plugins:
    css: { autoprefixer: { } }
    img: { optim: { } }
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  - scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: /posts/page/:num/
permalink: posts/:slug
